image:
  repository: ghcr.io/gettuned/docker/sendgrid-mock
  tag: main
  pullPolicy: Always
  secret: github-registry-secret

readinessProbe:
  initialDelaySeconds: 45
  periodSeconds: 15
  timeoutSeconds: 40
  failureThreshold: 30

livenessProbe:
  initialDelaySeconds: 45
  periodSeconds: 15
  timeoutSeconds: 40
  failureThreshold: 30

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
