apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    helm.sh/chart: {{ include "tuned.common.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.ingress.sslRedirect }}"
    {{- if .Values.ingress.stripPath }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "{{ .Values.ingress.rewriteTarget }}"
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ if .Values.ingress.stripPath }}"/{{ default .Values.app.name .Values.ingress.prefix }}(/|$)(.*)"{{ else }}"/{{ default .Values.app.name .Values.ingress.prefix }}"{{ end }}
            pathType: {{ if .Values.ingress.stripPath }}{{ .Values.ingress.stripPathType }}{{ else }}{{ .Values.ingress.pathType }}{{ end }}
            backend:
              service:
                name: {{ .Values.app.name }}
                port:
                  number: 80