replicas: 1
revisionHistoryLimit: 1

app:
  name: mcp-service
  port: 3000
  profiles: nonprod

image:
  repository: ghcr.io/gettuned
  tag: main
  pullPolicy: Always
  secret: github-registry-secret

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 10
  failureThreshold: 5

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 5

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 20m
    memory: 64Mi
