replicas: 1
revisionHistoryLimit: 1

app:
  name: graphql-router
  healthEndpoint: /health

image:
  repository: ghcr.io/gettuned
  tag: main
  pullPolicy: Always
  secret: github-registry-secret

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 15
  failureThreshold: 5

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 15
  failureThreshold: 5

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 60m
    memory: 256Mi
